sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - shellcheck

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - ./bin/build
  - ./bin/start

script:
  - ./bin/test
