version: '3.4'
services:
  db:
    image: 'mariadb:10.3'
    restart: always
    ports:
     - '3306:3306'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './data/services/db:/var/lib/mysql'
      - './services/db/conf:/etc/mysql/conf.d'
    environment:
      MYSQL_ROOT_PASSWORD: '${MAISON_SQLDB_ROOT_PASSWORD}'
