#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

./bin/await

set +a
. ./.env
set -a

container_ip=$(docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' bridge)
mysql -h "$container_ip" -u root "-p$MAISON_SQLDB_ROOT_PASSWORD"
